name             'open_call'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures open_call'
long_description 'Installs/Configures open_call'
version          '0.1.0'

depends 'git', '~> 4.3.4'
depends 'rbenv', '~> 1.7.1'
depends 'java', '~> 1.36.0'
depends 'nodejs', '~> 2.4.2'
depends 'elasticsearch', '~> 1.2.0'
depends 'postgresql', '~> 3.4.21'
