name             'open_call'
maintainer       'Fernando Di Bartolo'
maintainer_email 'fernando.di.bartolo@gmail.com'
license          'All rights reserved'
description      'Installs/Configures open_call'
long_description 'Installs/Configures open_call'
version          '1.0.0'

depends 'git', '~> 8.0.0'
depends 'rbenv', '~> 1.7.1'
depends 'java', '~> 1.50.0'
depends 'nodejs', '~> 2.4.2'
depends 'postgresql', '~> 3.4.21'
